import type { Lesson, GameAction, GameState, ParseResult, StopReason } from '../types'

export const MAX_ACTIONS = 200

/**
 * Upper bound on loop-body iterations for a single run. Blockly injects
 * `__tick()` (see INFINITE_LOOP_TRAP in ../blockly/customBlocks.ts) at the top
 * of every loop body, so a loop that never moves the character — `while (true)
 * {}` or a sensor loop whose condition can never become false — still stops
 * cleanly instead of freezing the tab. 10k empty iterations run in well under a
 * frame.
 */
export const MAX_LOOP_TICKS = 10_000

/**
 * Position sensors report 1-based coordinates so the number a child reads off
 * the grid gutter is the number the block returns. The engine itself stays
 * 0-based; the origin is applied at the sensor boundary only.
 */
export const COORD_ORIGIN = 1

/** Statement injected into every loop body by Blockly's infinite-loop trap. */
export const LOOP_GUARD_STATEMENT = '__tick();\n'

/** Remove the loop guard from generated code before showing it to a child. */
export function stripLoopGuard(code: string): string {
  return code.replace(/^[ \t]*__tick\(\);\r?\n/gm, '')
}

export function buildInitialState(lesson: Lesson): GameState {
  return {
    charPos: [...lesson.startPos] as [number, number],
    collectedIds: new Set<string>(),
    status: 'idle',
    blockCount: 0,
    steps: 0,
  }
}

/**
 * Identifiers shadowed to `undefined` inside the sandbox.
 *
 * `new Function(...)` compiles its body in global scope, so without this the
 * generated code could still reach `window`, `fetch`, or `localStorage` by
 * name. Passing each one as an extra parameter with no argument binds it to
 * `undefined` for the whole body, which is what makes INV-G4's "no access to
 * window, document, fetch, or localStorage" literally true rather than a
 * statement about the five verbs. Combined with the `'use strict'` prologue
 * (which leaves `this` undefined and stops the callee reaching the global
 * object that way), the only names generated code can resolve are the seven
 * the engine supplies.
 *
 * `eval` and `import` are absent because neither is a legal parameter name —
 * `eval` is banned in a strict-mode parameter list and `import` is a reserved
 * word. Direct `eval` still resolves through this shadowed scope, so it
 * reaches the same `undefined` bindings. This is defence in depth for a
 * closed input space (every line of code here is generated by blocks this app
 * defines), not a hardened security boundary — prototype walks such as
 * `[].constructor.constructor` cannot be shadowed away.
 */
const SHADOWED_GLOBALS = [
  'globalThis', 'window', 'self', 'top', 'parent', 'frames', 'document',
  'location', 'history', 'navigator', 'fetch', 'XMLHttpRequest', 'WebSocket',
  'EventSource', 'sendBeacon', 'localStorage', 'sessionStorage', 'indexedDB',
  'caches', 'cookieStore', 'Function', 'require',
  'importScripts', 'process', 'Worker', 'SharedWorker', 'WebAssembly',
  'postMessage', 'open', 'alert', 'confirm', 'prompt',
  'setTimeout', 'setInterval', 'requestAnimationFrame', 'queueMicrotask',
] as const

/**
 * Private sentinel used to unwind generated code when a run must stop. It is
 * caught inside parseCodeToActions and never surfaced as a code error — a
 * halted run is a gameplay outcome, not a bug in the child's blocks.
 */
class Halt {
  constructor(readonly reason: StopReason) {}
}

/**
 * Run block-generated code and collect the actions it produces.
 *
 * The run is a headless simulation: every movement verb is applied through the
 * same `applyAction` reducer the animation uses, so the position a sensor
 * reports is exactly the position the character will occupy at that point of
 * the replay. Bounds (INV-G1) and obstacle (INV-G2) rules therefore have a
 * single implementation.
 *
 * INV-G4 — the sandbox exposes exactly seven usable names: the four movement
 * verbs, the two read-only position sensors, and the loop guard. Every global
 * in SHADOWED_GLOBALS is bound to `undefined`, so `window`, `document`,
 * `fetch` and `localStorage` are unreachable by name.
 */
export function parseCodeToActions(code: string, lesson: Lesson): ParseResult {
  const actions: GameAction[] = []
  let error: string | undefined
  let stopped: StopReason | undefined
  let state = buildInitialState(lesson)
  let ticks = 0

  const pushAction = (type: GameAction['type']) => {
    // INV-G3 — no run may produce more than MAX_ACTIONS actions.
    if (actions.length >= MAX_ACTIONS) throw new Halt('action-cap')
    actions.push({ type })
    state = applyAction(state, { type }, lesson)
    // A crash ends the run here; the recorded action still replays and crashes
    // identically during the animation.
    if (state.status === 'crashed') throw new Halt('crashed')
  }

  const moveRight = () => { pushAction('move_right') }
  const moveLeft = () => { pushAction('move_left') }
  const moveUp = () => { pushAction('move_up') }
  const moveDown = () => { pushAction('move_down') }
  const currentRow = () => state.charPos[0] + COORD_ORIGIN
  const currentCol = () => state.charPos[1] + COORD_ORIGIN
  const __tick = () => {
    ticks += 1
    if (ticks > MAX_LOOP_TICKS) throw new Halt('loop-cap')
  }

  try {
    // eslint-disable-next-line no-new-func
    const fn = new Function(
      'moveRight', 'moveLeft', 'moveUp', 'moveDown',
      'currentRow', 'currentCol', '__tick',
      ...SHADOWED_GLOBALS,
      `'use strict';\n${code}`
    )
    // The shadowed names are deliberately left unbound (undefined).
    fn(moveRight, moveLeft, moveUp, moveDown, currentRow, currentCol, __tick)
  } catch (e) {
    if (e instanceof Halt) {
      stopped = e.reason
    } else {
      error = e instanceof Error ? e.message : 'Code error'
    }
  }

  return { actions, error, stopped }
}

export function applyAction(
  state: GameState,
  action: GameAction,
  lesson: Lesson
): GameState {
  const [row, col] = state.charPos
  let newRow = row
  let newCol = col

  switch (action.type) {
    case 'move_right': newCol = col + 1; break
    case 'move_left':  newCol = col - 1; break
    case 'move_up':    newRow = row - 1; break
    case 'move_down':  newRow = row + 1; break
  }

  // Bounds check
  if (newRow < 0 || newRow >= lesson.gridRows || newCol < 0 || newCol >= lesson.gridCols) {
    return { ...state, status: 'crashed', errorMessage: 'Oops! Walked off the edge! 🚧', steps: state.steps + 1 }
  }

  // Obstacle check
  if (lesson.cells[newRow]?.[newCol] === 'obstacle') {
    return { ...state, status: 'crashed', errorMessage: 'Crashed into an obstacle! 💥', steps: state.steps + 1 }
  }

  // Auto-collect items at new position
  const itemsAtNew = lesson.items.filter(
    i => i.pos[0] === newRow && i.pos[1] === newCol && !state.collectedIds.has(i.id)
  )
  const newCollected = new Set(state.collectedIds)
  itemsAtNew.forEach(i => newCollected.add(i.id))

  return {
    ...state,
    charPos: [newRow, newCol],
    collectedIds: newCollected,
    steps: state.steps + 1,
  }
}

export function checkWin(state: GameState, lesson: Lesson): boolean {
  if (lesson.goalType === 'collect_all') {
    return lesson.items.every(i => state.collectedIds.has(i.id))
  }
  if (lesson.goalType === 'reach_goal' && lesson.goalPos) {
    return state.charPos[0] === lesson.goalPos[0] && state.charPos[1] === lesson.goalPos[1]
  }
  if (lesson.goalType === 'collect_any' && lesson.goalCount) {
    return state.collectedIds.size >= lesson.goalCount
  }
  return false
}
